"""add stuff to user model

Revision ID: 0c1f1e0d19fd
Revises: d58eee9a2fd0
Create Date: 2026-02-01 12:32:42.722865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1f1e0d19fd'
down_revision: Union[str, Sequence[str], None] = 'd58eee9a2fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'is_staff',
            sa.Boolean(),
            server_default='0',
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###
