"""empty message

Revision ID: 967aa19308cf
Revises: 0c1f1e0d19fd
Create Date: 2026-02-02 15:40:06.419792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967aa19308cf'
down_revision: Union[str, Sequence[str], None] = '0c1f1e0d19fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_stuff', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    op.drop_column('user', 'is_stuff')
    # ### end Alembic commands ###
